### ISSUE TITLE
Server script fra tberterlsen.dk over https

### ISSUE THREAD

**Issue by homburg** [tbertelsen/castdr#6]
Hej

Bookmarklet'en bliver forhindret i af fungere i kraft af at dr.dk/tv forcerer https

Tilføj et certifikat på tbertelsen.dk, fx fra https://cert.startcom.org/ så scriptet kan serveres over https

Du kan bruge en protocol-relative url for a dække http og https:

```
<script src="//tbertelsen.dk/castdr/js/bookmarklet.js" id="drcastbookmarklet" type="text/javascript"></script>
```

**Comment by homburg** [comment]
Du kan evt også servere via https://rawgit.com/

**Comment by tbertelsen** [comment]
Shit den var værre.
Tak for info. Jeg vil begynde at serve gennem cloudflare, og venter på SSL certifikatet i øjeblikket.
Håber at jeg kan få det op og køre i aften.

**Comment by homburg** [comment]
NP, godt arbejde :-)

**Comment by tbertelsen** [comment]
Så HTTPS online på https://castdr.tbertelsen.dk
Backenden er skiftet til github-pages via cloudflare
