### ISSUE TITLE
castdr live igen?

### ISSUE THREAD

**Issue by dtronier** [tbertelsen/castdr#7]
@tbertelsen 

Hej Tobias

Det ser ud til, at castdr er nede. Er der planer for at få det op at køre igen?

Dbh Daniel

**Comment by tbertelsen** [comment]
Kan du forklare lidt mere om hvad du har gjort, og hvad der går galt? (Evt
fejl beskeder osv.)

**Comment by dtronier** [comment]
![skaermbillede 2015-06-19 kl 21 45 58](https://cloud.githubusercontent.com/assets/5322792/8261664/908ed320-16cc-11e5-97dc-0d26077dd908.png)

**Comment by tbertelsen** [comment]
Prøv at rydde din cache og gå ind på castdr.tbertelsen.dk

**Comment by dtronier** [comment]
Det virkede tak. Jeg ville sætte en redirect på tbertelsen.dk/castdr, hvis jeg var dig. Mange links, der peger den vej.

**Comment by tbertelsen** [comment]
Super. Redirectsne er nu genoprettet.
